name: 'Generaete Dependency CSV File'
description: 'Generates a csv file that contains a list of the depenencies detected in the specified repo.'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    default: ${{ github.token }}
    required: false
  repo-name:
    description: 'The name of the repo to list (default is current repo e.g. thedave42/generate-depenencies-csv-action)'
    default: ${{ github.repository }}
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'