on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    name: Genereate a list of dependencies for this repository
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          
    - name: Generate dependencies action
      uses: ./ # Uses an action in the root directory   