on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Genereate a list of dependencies for this repository
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate dependencies action
      uses: ./ # Uses an action in the root directory   